SELECT
  TAB_CADASTRO.INSTALACAO AS CR_NUMERO,
  CONSUMIDOR.INSTALACAO_ID AS INSTALACAO_ID,
  TRY_CAST(TAB_CADASTRO.CONTRATO AS INTEGER) AS CONTRATO,
  TRY_CAST(TAB_CADASTRO.CONTA_CONTRATO AS INTEGER) AS CONTA_CONTRATO,
  TRY_CAST(TAB_CADASTRO.MEDIDOR AS INTEGER) AS MEDIDOR_ID,
  TAB_CADASTRO.TIPO_LOCAL_CONSUMO,
  TAB_CADASTRO.GENERO,
  TAB_CADASTRO.DATA_NASCIMENTO,
  TAB_CADASTRO.ESTADO_CIVIL,
  TAB_CADASTRO.LATITUDE,
  TAB_CADASTRO.LONGITUDE,
  TAB_CADASTRO.DATA_INSTALACAO_MEDIDOR
FROM
  (
    SELECT *
    FROM EQTLINFO_PRD.EQTL_PA.TAB_CADASTRO
    ORDER BY RANDOM()
    LIMIT 20
  ) TAB_CADASTRO
LEFT JOIN EQTLINFO_RAW.OPER_PA.CONSUMIDOR CONSUMIDOR 
  ON TAB_CADASTRO.INSTALACAO = LPAD(
    REGEXP_REPLACE(TO_VARCHAR(CONSUMIDOR.CR_NUMERO), '[^0-9]', ''),
    LENGTH(TAB_CADASTRO.INSTALACAO),
    '0'
  );